<?php

/**
 * @file
 * Install, and uninstall functions for the adyax_test module.
 */

/**
 * Implements hook_schema()
 */
function adyax_test_schema() {
  $schema['field_adyax_test'] = array(
    'description' => t('The table for adyax_test.'),
    'fields' => array(
      'id' => array(
        'description' => 'The primary identifier for a field.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE
      ),
      'nid' => array(
        'description' => 'The current node identifier.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0
      ),
      'field_value' => array(
        'description' => 'The value of this field.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => ''
      ),
    ),
    'unique keys' => array(
      'nid'     => array('nid')
      ),
    'primary key' => array('id'),
  );
  return $schema;
}

